In [ ]:
from google.colab import files
uploaded = files.upload()

Saving cancer patient data sets.csv to cancer patient data sets.csv


NameError: name 'pd' is not defined

In [ ]:
# Install necessary libraries
!pip install pandas numpy scikit-learn tensorflow



In [ ]:
import pandas as pd

# Load the dataset
df = pd.read_csv('cancer patient data sets.csv')
df.columns


Index(['Age', 'Gender', 'Air Pollution', 'Alcohol use', 'Dust Allergy',
       'OccuPational Hazards', 'Genetic Risk', 'chronic Lung Disease',
       'Balanced Diet', 'Obesity', 'Smoking', 'Passive Smoker', 'Chest Pain',
       'Coughing of Blood', 'Fatigue', 'Weight Loss', 'Shortness of Breath',
       'Wheezing', 'Swallowing Difficulty', 'Clubbing of Finger Nails',
       'Frequent Cold', 'Dry Cough', 'Snoring', 'Level'],
      dtype='object')

In [7]:
df.columns = df.columns.str.strip().str.upper()  # Removes spaces and makes uppercase
print(df.columns.tolist())


['AGE', 'GENDER', 'AIR POLLUTION', 'ALCOHOL USE', 'DUST ALLERGY', 'OCCUPATIONAL HAZARDS', 'GENETIC RISK', 'CHRONIC LUNG DISEASE', 'BALANCED DIET', 'OBESITY', 'SMOKING', 'PASSIVE SMOKER', 'CHEST PAIN', 'COUGHING OF BLOOD', 'FATIGUE', 'WEIGHT LOSS', 'SHORTNESS OF BREATH', 'WHEEZING', 'SWALLOWING DIFFICULTY', 'CLUBBING OF FINGER NAILS', 'FREQUENT COLD', 'DRY COUGH', 'SNORING', 'LEVEL']


In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score, classification_report


In [9]:
df.head()


AGE  GENDER  AIR POLLUTION  ALCOHOL USE  DUST ALLERGY  \
0   33       1              2            4             5   
1   17       1              3            1             5   
2   35       1              4            5             6   
3   37       1              7            7             7   
4   46       1              6            8             7   

   OCCUPATIONAL HAZARDS  GENETIC RISK  CHRONIC LUNG DISEASE  BALANCED DIET  \
0                     4             3                     2              2   
1                     3             4                     2              2   
2                     5             5                     4              6   
3                     7             6                     7              7   
4                     7             7                     6              7   

   OBESITY  ...  FATIGUE  WEIGHT LOSS  SHORTNESS OF BREATH  WHEEZING  \
0        4  ...        3            4                    2         2   
1        2  ...        1            3                    7         8   
2        7  ...        8            7                    9         2   
3        7  ...        4            2                    3         1   
4        7  ...        3            2                    4         1   

   SWALLOWING DIFFICULTY  CLUBBING OF FINGER NAILS  FREQUENT COLD  DRY COUGH  \
0                      3                         1              2          3   
1                      6                         2              1          7   
2                      1                         4              6          7   
3                      4                         5              6          7   
4                      4                         2              4          2   

   SNORING   LEVEL  
0        4     Low  
1        2  Medium  
2        2    High  
3        5    High  
4        3    High  

[5 rows x 24 columns]

In [10]:
print(df.isnull().sum())


AGE                         0
GENDER                      0
AIR POLLUTION               0
ALCOHOL USE                 0
DUST ALLERGY                0
OCCUPATIONAL HAZARDS        0
GENETIC RISK                0
CHRONIC LUNG DISEASE        0
BALANCED DIET               0
OBESITY                     0
SMOKING                     0
PASSIVE SMOKER              0
CHEST PAIN                  0
COUGHING OF BLOOD           0
FATIGUE                     0
WEIGHT LOSS                 0
SHORTNESS OF BREATH         0
WHEEZING                    0
SWALLOWING DIFFICULTY       0
CLUBBING OF FINGER NAILS    0
FREQUENT COLD               0
DRY COUGH                   0
SNORING                     0
LEVEL                       0
dtype: int64


In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   AGE                       1000 non-null   int64
 1   GENDER                    1000 non-null   int64
 2   AIR POLLUTION             1000 non-null   int64
 3   ALCOHOL USE               1000 non-null   int64
 4   DUST ALLERGY              1000 non-null   int64
 5   OCCUPATIONAL HAZARDS      1000 non-null   int64
 6   GENETIC RISK              1000 non-null   int64
 7   CHRONIC LUNG DISEASE      1000 non-null   int64
 8   BALANCED DIET             1000 non-null   int64
 9   OBESITY                   1000 non-null   int64
 10  SMOKING                   1000 non-null   int64
 11  PASSIVE SMOKER            1000 non-null   int64
 12  CHEST PAIN                1000 non-null   int64
 13  COUGHING OF BLOOD         1000 non-null   int64
 14  FATIGUE                   1000 non-null  

In [11]:
label_encoders = {}
for column in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[column] = le.fit_transform(df[column])
    label_encoders[column] = le


In [13]:
X = df.drop(columns=['LEVEL'])  # Features
y = df['LEVEL']                # Target variable


In [16]:
 X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)


In [17]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [19]:
 # Define and train the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [20]:
# Make predictions
y_pred = rf.predict(X_test)

# Evaluate
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        73
           1       1.00      1.00      1.00        61
           2       1.00      1.00      1.00        66

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200


Confusion Matrix:
 [[73  0  0]
 [ 0 61  0]
 [ 0  0 66]]


In [21]:
!pip install gradio




   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.5/46.5 MB 12.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 322.2/322.2 kB 20.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 86.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 4.5 MB/s eta 0:00:00


In [26]:
print(label_encoders.keys())


dict_keys(['LEVEL'])


In [39]:
df.columns

Index(['AGE', 'GENDER', 'AIR POLLUTION', 'ALCOHOL USE', 'DUST ALLERGY',
       'OCCUPATIONAL HAZARDS', 'GENETIC RISK', 'CHRONIC LUNG DISEASE',
       'BALANCED DIET', 'OBESITY', 'SMOKING', 'PASSIVE SMOKER', 'CHEST PAIN',
       'COUGHING OF BLOOD', 'FATIGUE', 'WEIGHT LOSS', 'SHORTNESS OF BREATH',
       'WHEEZING', 'SWALLOWING DIFFICULTY', 'CLUBBING OF FINGER NAILS',
       'FREQUENT COLD', 'DRY COUGH', 'SNORING', 'LEVEL'],
      dtype='object')

In [45]:
import gradio as gr


def predict_lung_cancer(age, gender, air_pollution, alcohol_use, dust_allergy,
                        occupational_hazards, genetic_risk, chronic_lung_disease,
                        balanced_diet, obesity, smoking, passive_smoker,
                        chest_pain, coughing_of_blood, fatigue, weight_loss,
                        shortness_of_breath, wheezing, swallowing_difficulty,
                        clubbing_of_finger_nails, frequent_cold, dry_cough, snoring):

    try:
        # Encode gender: assuming 'Male' = 1, 'Female' = 0
        gender_encoded = 1 if gender == 'Male' else 0

        input_data = [[age, gender_encoded, air_pollution, alcohol_use, dust_allergy,
                       occupational_hazards, genetic_risk, chronic_lung_disease,
                       balanced_diet, obesity, smoking, passive_smoker,
                       chest_pain, coughing_of_blood, fatigue, weight_loss,
                       shortness_of_breath, wheezing, swallowing_difficulty,
                       clubbing_of_finger_nails, frequent_cold, dry_cough, snoring]]

        prediction = rf.predict(input_data)[0]

        return f"Predicted Lung Cancer Risk Level: {prediction}"

    except Exception as e:
        return f"Error during prediction: {e}"


In [46]:
predict_lung_cancer(55, 'Male', 7, 5, 6, 5, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5)


'Predicted Lung Cancer Risk Level: 0'

In [47]:
 import gradio as gr

gr.Interface(
    fn=predict_lung_cancer,
    inputs=[
        gr.Number(label="Age"),
        gr.Dropdown(["Male", "Female"], label="Gender"),
        gr.Slider(1, 10, label="Air Pollution"),
        gr.Slider(1, 10, label="Alcohol Use"),
        gr.Slider(1, 10, label="Dust Allergy"),
        gr.Slider(1, 10, label="Occupational Hazards"),
        gr.Slider(1, 10, label="Genetic Risk"),
        gr.Slider(1, 10, label="Chronic Lung Disease"),
        gr.Slider(1, 10, label="Balanced Diet"),
        gr.Slider(1, 10, label="Obesity"),
        gr.Slider(1, 10, label="Smoking"),
        gr.Slider(1, 10, label="Passive Smoker"),
        gr.Slider(1, 10, label="Chest Pain"),
        gr.Slider(1, 10, label="Coughing of Blood"),
        gr.Slider(1, 10, label="Fatigue"),
        gr.Slider(1, 10, label="Weight Loss"),
        gr.Slider(1, 10, label="Shortness of Breath"),
        gr.Slider(1, 10, label="Wheezing"),
        gr.Slider(1, 10, label="Swallowing Difficulty"),
        gr.Slider(1, 10, label="Clubbing of Finger Nails"),
        gr.Slider(1, 10, label="Frequent Cold"),
        gr.Slider(1, 10, label="Dry Cough"),
        gr.Slider(1, 10, label="Snoring")
    ],
    outputs=gr.Text(label="Prediction Result"),
    title="Lung Cancer Risk Prediction",
    description="Enter patient health metrics to predict lung cancer risk using a trained Random Forest model."
).launch(share=True)


Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://f592ddb01b743eac02.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)
